// (C) 2025 Brad Colbert
#ifndef __DISPLAY_LIST_ANTICF_H__
#define __DISPLAY_LIST_ANTICF_H__

#include "playfield.h"

#include <atari.h>

// Defines
#define TILE_NUM 0

// Globals
extern tile_struct row_zero[]; // 4080 bytes for the first part (102 lines of 40 bytes each)

void display_list_anticF =
{
    DL_BLK8,
    DL_BLK8,
    DL_BLK8,

    DL_LMS(DL_GRAPHICS8), &row_zero[TILE_NUM].data[0][16], DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8,
    DL_LMS(DL_GRAPHICS8), &row_one[TILE_NUM].data[0][0], DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,  
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,

    DL_JVB, &display_list_anticF
};

#endif // __DISPLAY_LIST_ANTIC4_H__