#ifndef GRAPHICS_8_DL_H
#define GRAPHICS_8_DL_H

#include <atari.h>

void graphics_8_dl = {
    DL_BLK8,
    DL_BLK8,
    DL_BLK8,
    DL_LMS(DL_GRAPHICS8), &framebuffer[0], DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8,
    DL_LMS(DL_GRAPHICS8), &framebuffer[4096], DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,  
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8, DL_GRAPHICS8,
    DL_JVB, &graphics_8_dl
};

#endif // GRAPHICS_8_DL_H
